
global main_root = '';
global dialog = '';

global faq_score = 0.2;
global conv_score = 0.5;

global train_state_path = 'utils/data/state.json';
global train_faq_answer_path = 'utils/data/faq_answer.json';
global train_classifer_path = 'utils/data/classifer_data.json';
global train_tfn_ner_path = 'utils/data/tfm_train.json';

// global entity_label =['number', 'account_name', 'month'];
global entity_label =[];

