import {*} with "./training_app/training_graph.jac";
import {*} with "./conv_app/conv_graph.jac";

// node conv_root;

// edge conv_root;




// graph app_graph {
//     has anchor training_root_t;
//     spawn {
//         training_root_t = spawn node::training_root_t;
//         // intent_root_t = spawn training_root_t ++> node::intent_root_t;
//         // faq_root_1 = spawn training_root_t +[faq_root_1]+> node::faq_root_1;
//     }
// }